controledental/base/urls.py
from django.urls import path

from controledental.base.views import home


app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

controledental/tratamento/urls.py
from django.urls import path

from controledental.tratamento import views


app_name = 'tratamento'
urlpatterns = [
    path('', views.tratamentos, name='tratamento'),
]

controledental/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('controledental.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

controledental/tratamento/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from controledental.cadastrotratamento.models import CadastroTratamento


class Tratamento(models.Model):
    class Meta:
        verbose_name = 'Tratamento'
        verbose_name_plural = 'Tratamentos'

    paciente = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)
    tratamento = models.ForeignKey(CadastroTratamento, on_delete=models.CASCADE, verbose_name='Tratamento',
                                   default=None,)
    DENTE = [

        ("0-TODOS", "TODOS"),
        ("11-INCISIVO CENTRAL SUPERIOR", "11-INCISIVO CENTRAL SUPERIOR"),
        ("21-INCISIVO CENTRAL SUPERIOR", "21-INCISIVO CENTRAL SUPERIOR"),
        ("12-INCISIVO LATERAL SUPERIOR", "12-INCISIVO LATERAL SUPERIOR"),
        ("22-INCISIVO LATERAL SUPERIOR", "22-INCISIVO LATERAL SUPERIOR"),
        ("13-CANINO SUPERIOR", "13-CANINO SUPERIOR"),
        ("23-CANINO SUPERIOR", "23-CANINO SUPERIOR"),
        ("14-PRE-MOLAR SUPERIOR", "14-PRE-MOLAR SUPERIOR"),
        ("15-PRE-MOLAR SUPERIOR", "15-PRE-MOLAR SUPERIOR"),
        ("24-PRE-MOLAR SUPERIOR", "24-PRE-MOLAR SUPERIOR"),
        ("25-PRE-MOLAR SUPERIOR", "25-PRE-MOLAR SUPERIOR"),
        ("16-MOLAR SUPERIOR", "16-MOLAR SUPERIOR"),
        ("17-MOLAR SUPERIOR", "17-MOLAR SUPERIOR"),
        ("18-MOLAR SUPERIOR", "18-MOLAR SUPERIOR"),
        ("26-MOLAR SUPERIOR", "26-MOLAR SUPERIOR"),
        ("27-MOLAR SUPERIOR", "27-MOLAR SUPERIOR"),
        ("28-MOLAR SUPERIOR", "28-MOLAR SUPERIOR"),
        ("31-INCISIVO CENTRAL INFERIOR", "31-INCISIVO CENTRAL INFERIOR"),
        ("41-INCISIVO CENTRAL INFERIOR", "41-INCISIVO CENTRAL INFERIOR"),
        ("32-INCISIVO LATERAL INFERIOR", "32-INCISIVO LATERAL INFERIOR"),
        ("42-INCISIVO LATERAL INFERIOR", "42-INCISIVO LATERAL INFERIOR"),
        ("33-CANINO INFERIOR", "33-CANINO INFERIOR"),
        ("43-CANINO INFERIOR", "43-CANINO INFERIOR"),
        ("34-PRE MOLAR INFERIOR", "34-PRE MOLAR INFERIOR"),
        ("35-PRE MOLAR INFERIOR", "35-PRE MOLAR INFERIOR"),
        ("44-PRE MOLAR INFERIOR", "44-PRE MOLAR INFERIOR"),
        ("45-PRE MOLAR INFERIOR", "45-PRE MOLAR INFERIOR"),
        ("36-MOLAR INFERIOR", "36-MOLAR INFERIOR"),
        ("37-MOLAR INFERIOR", "37-MOLAR INFERIOR"),
        ("38-MOLAR INFERIOR", "38-MOLAR INFERIOR"),
        ("46-MOLAR INFERIOR", "46-MOLAR INFERIOR"),
        ("47-MOLAR INFERIOR", "47-MOLAR INFERIOR"),
        ("48-MOLAR INFERIOR", "48-MOLAR INFERIOR"),
    ]
    dente = models.CharField(max_length=60, choices=DENTE, verbose_name='Dente')
    observacao = models.CharField(max_length=5000, verbose_name="Observação")
    valor_tratamento = models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor', null=False, default=0)
    data_tratamento = models.DateField(verbose_name="Data Tratamento", default=timezone.now)

    def __repr__(self):
        return f'paciente{self.paciente},tratamento{self.tratamento}, datatratamento{self.data_tratamento}' \
               f', observacao={self.observacao!r}'

controledental/tratamento/views.py
# from django.shortcuts import render
#
# from controledental.tratamento.models import Tratamento
#
#
# def tratamentos(request):
#     query_set = Tratamento.objects.order_by('nome')
#     ctx = {
#         'Tratamentos': list(query_set)
#     }
#     return render(request, 'tratamento/tratamento.html', context=ctx)

controledental/tratamento/templates/tratamento/tratamentos.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Pacientes</title>

    <meta name="description" content="Página para controle de tratamentos">
    <meta name="author" content="João Garcia">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'base:home' %}">Controle Dental</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tratamentos:tratamentos' %}">Pacientes</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>


<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Nome tratamento</th>

    </tr>
    </thead>

    <tbody>
    {% for tratamento in Tratamentos %}
        <tr>
            <td>{{ tratamento.nome }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{#{% else %}#}
{#<div class="text-center mt-5 mb-5 jumbotron">#}
{#    <h5>Nenhum <code>Paciente</code> cadastrado ainda.</h5>#}
{#</div>#}
{#{% endif %}#}

{#<div class="text-right">#}
{#    <a href="{% url 'CadastroFuncionario' %}" class="btn btn-primary">#}
{#        Cadastrar Funcionário#}
{#    </a>#}
{#</div>#}

</body>
</html>